routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');


Route::get('/posts/{id}', 'HomeController@showPost')->name('post');
Route::get('/logout','Auth\LoginController@logout')->name('logout');


Route::prefix('admin')->name('admin.')->middleware(['auth'])->group(function () {

    Route::get('/', 'BlogPostController@index')->name('index');
    Route::post('/upload_image', 'BlogPostApiController@uploadImage')->name('uploadimage');

});

Route::apiResource('blogposts','BlogPostApiController');

app/Models/BlogPost.php
<?php

namespace App\Models;

use App\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;


class BlogPost extends Eloquent
{
    protected $connection = 'mongodb';
    protected $collection = 'blog_posts';


    protected $fillable = [
        'title', 'intro','content','published','user_id'
    ];


    public static $store_validation_rules = [
        'title'         => 'required',
        'intro'         => 'required',
        'content'       => 'required',


    ];

    public static $update_validation_rules = [
        'title'         => 'required',
        'intro'         => 'required',
        'content'       => 'required',


    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function scopePublished($query)
    {
        return $query->where('published',true);
    }


}

app/User.php
<?php

namespace App;

use App\Models\BlogPost;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function blogPosts()
    {
        return $this->hasMany(BlogPost::class);
    }
}

app/Http/Controllers/BlogPostApiController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\BlogPostStoreRequest;
use App\Models\BlogPost;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;

class BlogPostApiController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blogposts = BlogPost::paginate(5);
        return $blogposts;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $r, BlogPostStoreRequest $request)
    {
        $data = $request->validated();
        $data['published']  = ($r->published=='true')?true:false;
        $data['user_id']  = auth()->user()->id;
        $blogpost = BlogPost::create($data);
        return $blogpost;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $blogpost = BlogPost::findOrFail($id);
        return $blogpost;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $r, BlogPostStoreRequest $request, $id)
    {
        $blogpost = BlogPost::findOrFail($id);

        $data = $request->validated();
        $data['published']  = ($r->published=='true')?true:false;
        $data['user_id']  = auth()->user()->id;
        $blogpost->fill($data);
        $blogpost->save();
        return $blogpost;
    }



    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $blogpost = BlogPost::findOrFail($id);
        $blogpost->delete();
        return ['status'=>true];
    }
}

app/Http/Controllers/BlogPostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\BlogPostStoreRequest;
use App\Http\Requests\BlogPostUpdateRequest;
use App\Models\BlogPost;
use Illuminate\Http\Request;

class BlogPostController extends Controller
{

    public function index()
    {
        $blogposts = BlogPost::paginate(10);
        return view('blog_posts.index',compact('blogposts'));
    }

    public function create(Request $request)
    {
        return view('blog_posts.create');
    }

    public function store(Request $r, BlogPostStoreRequest $request)
    {
        $data = $request->validated();
        $data['published']  = ($r->published=='true')?true:false;
        $data['user_id']  = auth()->user()->id;
        BlogPost::create($data);
        return redirect()->route('admin.blogposts.index')->with('success',__('blog_posts.create_success'));

    }

    public function edit($id)
    {
        $blogpost = BlogPost::findOrFail($id);
        return view('blog_posts.edit',compact('blogpost'));
    }

    public function update(Request $r,BlogPostUpdateRequest $request,$id)
    {
        $blogpost = BlogPost::findOrFail($id);
        $data = $request->validated();
        $data['published']  = ($r->published=='true')?true:false;
        $data['user_id']  = auth()->user()->id;
        $blogpost->update($data);
        return redirect()->route('admin.blogposts.index')->with('success',__('blog_posts.update_success'));
    }

    public function destroy($id)
    {
        $blogpost = BlogPost::findOrFail($id);
        $blogpost->delete();
        return redirect()->route('admin.blogposts.index')->with('success',__('blog_posts.delete_success'));

    }


}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\BlogPost;
use Illuminate\Http\Request;

class HomeController extends Controller
{


    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $blogposts = BlogPost::published()->paginate(3);
        return view('index',compact('blogposts'));
    }

    public function showPost($id)
    {
        $post = BlogPost::findOrFail($id);
        return view('post',compact('post'));
    }


}

resources/views/blog_posts/create.blade.php
@extends('layouts.admin')
    @section('content')
    <h2>Create Blog Post</h2><br/>
    @php
        $form_fields = [
            [
                'name'      => 'title',
                'type'      => 'text',
                'label'     => 'Title',
                'value'     => ''
            ],
            [
                'name'      => 'intro',
                'type'      => 'text',
                'label'     => 'Introduction',
                'value'     => ''
            ],
            [
                'name'      => 'content',
                'type'      => 'textarea',
                'label'     => 'Content',
                'value'     => ''
            ],

            [
                'name'      => 'published',
                'type'      => 'boolean',
                'label'     => 'Published',
                'value'     => false
            ]

        ];
    @endphp
    <form method="post" action="{{route('admin.blogposts.create')}}">
        @include('includes.form')
    </form>
    @endsection

resources/views/blog_posts/edit.blade.php
@extends('layouts.admin')
@section('content')
    <h2>Edit Blog Post</h2><br/>
    @php
        $form_fields = [
            [
                'name'      => 'title',
                'type'      => 'text',
                'label'     => 'Title',
                'value'     => $blogpost->title
            ],
            [
                'name'      => 'intro',
                'type'      => 'text',
                'label'     => 'Introduction',
                'value'     => $blogpost->intro
            ],
            [
                'name'      => 'content',
                'type'      => 'textarea',
                'label'     => 'Content',
                'value'     => $blogpost->content
            ],

            [
                'name'      => 'published',
                'type'      => 'boolean',
                'label'     => 'Published',
                'value'     => $blogpost->published
            ]

        ];
    @endphp
    <form method="post" action="{{route('admin.blogposts.update',['id'=>$blogpost->id])}}">
        @include('includes.form')
    </form>
@endsection

resources/views/blog_posts/index.blade.php
@extends('layouts.admin')



@section('content')



    <admin-blogpost-index-component></admin-blogpost-index-component>

    <blogpost-modal-component></blogpost-modal-component>


@endsection

@section('scripts')


@endsection

@section('footer-scripts')
    @parent



@endsection

resources/views/home.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/includes/form.blade.php
        @section('scripts')
            @parent

            <script src="https://cloud.tinymce.com/5/tinymce.min.js"></script>

        @endsection

        @csrf
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        @foreach($form_fields as $field)
            @switch($field['type'])
                @case('date')
                    {!! form_date_field($field['name'],$field['label'],$field['value']) !!}
                @break
                @case('boolean')
                    {!! form_boolean_field($field['name'],$field['label'],$field['value']) !!}
                @break
                @case('textarea')
                    {!! form_textarea_field($field['name'],$field['label'],$field['value']) !!}
                @break


                @default
                {!! form_text_field($field['name'],$field['label'],$field['value']) !!}
            @endswitch
        @endforeach



        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <button type="submit" class="btn btn-success">Save</button>
            </div>
        </div>

resources/views/index.blade.php
@extends('layouts.public')
@section('header')
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Figured</h1>
            <span class="subheading">Example Blog</span>
          </div>
        </div>
      </div>
    </div>
  </header>
@endsection
@section('content')
  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        @foreach($blogposts as $post)
        <div class="post-preview">
          <a href="{{route('post',['id'=>$post->id])}}">
            <h2 class="post-title">
              {{$post->title}}
            </h2>
            <h3 class="post-subtitle">
              {{$post->intro}}
            </h3>
          </a>
          <p class="post-meta">Posted
            <a href="#">@if($user=App\User::find($post->user_id)) by {{$user->name}} @endif</a>
            on {{$post->updated_at->toCookieString()}}</p>
        </div>
        <hr>
        @endforeach

        <!-- Pager -->
        <div class="clearfix text-center">
          {!! $blogposts->links() !!}
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Laravel MongoDB CRUD Tutorial With Example</title>
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">



    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>


    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
    <style type="text/css">
        .pagination {
            display: inline-block;
            padding-left: 0;
            margin: 20px 0;
            border-radius: 4px;
        }
        .pagination > li {
            display: inline;
        }
        .pagination > li > a,
        .pagination > li > span {
            position: relative;
            float: left;
            padding: 6px 12px;
            margin-left: -1px;
            line-height: 1.42857143;
            color: #337ab7;
            text-decoration: none;
            background-color: #fff;
            border: 1px solid #ddd;
        }
        .pagination > li:first-child > a,
        .pagination > li:first-child > span {
            margin-left: 0;
            border-top-left-radius: 4px;
            border-bottom-left-radius: 4px;
        }
        .pagination > li:last-child > a,
        .pagination > li:last-child > span {
            border-top-right-radius: 4px;
            border-bottom-right-radius: 4px;
        }
        .pagination > li > a:hover,
        .pagination > li > span:hover,
        .pagination > li > a:focus,
        .pagination > li > span:focus {
            z-index: 2;
            color: #23527c;
            background-color: #eee;
            border-color: #ddd;
        }
        .pagination > .active > a,
        .pagination > .active > span,
        .pagination > .active > a:hover,
        .pagination > .active > span:hover,
        .pagination > .active > a:focus,
        .pagination > .active > span:focus {
            z-index: 3;
            color: #fff;
            cursor: default;
            background-color: #337ab7;
            border-color: #337ab7;
        }
        .pagination > .disabled > span,
        .pagination > .disabled > span:hover,
        .pagination > .disabled > span:focus,
        .pagination > .disabled > a,
        .pagination > .disabled > a:hover,
        .pagination > .disabled > a:focus {
            color: #777;
            cursor: not-allowed;
            background-color: #fff;
            border-color: #ddd;
        }
        .pagination-lg > li > a,
        .pagination-lg > li > span {
            padding: 10px 16px;
            font-size: 18px;
            line-height: 1.3333333;
        }
        .pagination-lg > li:first-child > a,
        .pagination-lg > li:first-child > span {
            border-top-left-radius: 6px;
            border-bottom-left-radius: 6px;
        }
        .pagination-lg > li:last-child > a,
        .pagination-lg > li:last-child > span {
            border-top-right-radius: 6px;
            border-bottom-right-radius: 6px;
        }
        .pagination-sm > li > a,
        .pagination-sm > li > span {
            padding: 5px 10px;
            font-size: 12px;
            line-height: 1.5;
        }
        .pagination-sm > li:first-child > a,
        .pagination-sm > li:first-child > span {
            border-top-left-radius: 3px;
            border-bottom-left-radius: 3px;
        }
        .pagination-sm > li:last-child > a,
        .pagination-sm > li:last-child > span {
            border-top-right-radius: 3px;
            border-bottom-right-radius: 3px;
        }
    </style>

    @yield('scripts')

    <style type="text/css">
        /* Add a black background color to the top navigation */
        .topnav {
            background-color: #333;
            overflow: hidden;
        }

        /* Style the links inside the navigation bar */
        .topnav a {
            float: left;
            color: #f2f2f2;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 17px;
        }

        /* Change the color of links on hover */
        .topnav a:hover {
            background-color: #ddd;
            color: black;
        }

        /* Add a color to the active/current link */
        .topnav a.active {
            background-color: #4CAF50;
            color: white;
        }
    </style>
</head>
<body>
<div id="app">

        <div class="topnav">
            <a class="active" href="{{route('home')}}">Home</a>
            <a href="#" v-b-modal.modalxl v-b-modal.modal1 >Create Post</a>
            <ahref="{{route('logout')}}">Logout {{Auth::user()->name}}</a>
        </div>



    <div class="container">

        @if (\Session::has('success'))
            <div class="alert alert-success">
                <p>{{ \Session::get('success') }}</p>
            </div><br />
        @endif
        @if (\Session::has('error'))
            <div class="alert alert-success">
                <p>{{ \Session::get('error') }}</p>
            </div><br />
        @endif


        @yield('content')


    </div>

</div>
@yield('footer-scripts')
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/public.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Example Blog - Rudi Ullon</title>

    <!-- Bootstrap core CSS -->
    <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="/css/clean-blog.min.css" rel="stylesheet">

</head>

<body>
<div id="app">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{{route('home')}}">Blog</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    @if(Auth()->user())
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('admin.index')}}">Admin</a>
                    </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Header -->
    @yield('header')


    <!-- Main Content -->
    @yield('content')


    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="#">
                    <span class="fa-stack fa-lg">
                      <i class="fas fa-circle fa-stack-2x"></i>
                      <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                    </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                    <span class="fa-stack fa-lg">
                      <i class="fas fa-circle fa-stack-2x"></i>
                      <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                    </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://bitbucket.org/scretch/figured">
                    <span class="fa-stack fa-lg">
                      <i class="fas fa-circle fa-stack-2x"></i>
                      <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                    </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Rudi Ullón 2019</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="/vendor/jquery/jquery.min.js"></script>
    <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="/js/clean-blog.min.js"></script>
</div>
</body>

</html>

resources/views/post.blade.php
@extends('layouts.public')
@section('header')

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('/img/post-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-heading">
            <h1>{{$post->title}}</h1>
            <h2 class="subheading">{{$post->intro}}</h2>
            <span class="meta">Posted by
              <a href="#">Start Bootstrap</a>
              on August 24, 2019</span>
          </div>
        </div>
      </div>
    </div>
  </header>
@endsection
@section('content')
  <!-- Post Content -->
  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
         {!! $post->content !!}
        </div>
      </div>
    </div>
  </article>
@endsection